name: Build and publish release gem
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # v1 because of https://github.com/actions/checkout/issues/334
        with:
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      - name: "Install dev packages"
        run: |
          sudo apt-get install libxml2-dev libxml2 libxslt1-dev libxslt1.1 zlib1g zlib1g-dev libc6-dev -yq
      - run: |
          eval "$(~/.rbenv/bin/rbenv init - bash)"
          scripts/build-gems
      - name: "Setup Gem Credentials"
        run: |
          echo "Setting up gem credentials..."
          set +x
          mkdir -p ~/.gem

          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${{secrets.GITHUB_TOKEN}}
          EOF

          chmod 0600 ~/.gem/credentials
          set -x
      - name: Upload gems
        run: |
          for g in gems/*.gem ; do gem push --key github --host https://rubygems.pkg.github.com/commitchange $g ; done
